apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: the-finance-genie
  name: the-finance-genie-pvc
  namespace: the-finance-genie
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi