apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  namespace: the-finance-genie
spec:
  selector:
    matchLabels:
      app: ollama
  serviceName: "ollama"
  template:
    spec:
      containers:
      - name: ollama
        resources:
          limits:
            nvidia.com/gpu: "1"
